version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:15.1

step_restore_cache: &restore_cache
  restore_cache:
    keys:
      - node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: yarn install --production --frozen-lockfile --no-lockfile

step_save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
      - packages/cli/node_modules
      - packages/core/node_modules
      - packages/cli-plugin-init/node_modules
      - packages/cli-plugin-add/node_modules
      - packages/cli-plugin-lint/node_modules
      - ~/.cache/yarn
    key: node-deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run: yarn run test --ci

workflows:
  orb-free-workflow:
    jobs:
      - test
