version: 2

defaults: &defaults
  docker:
    - image: circleci/node:lts-browsers

step_restore_cache: &restore_cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "yarn.lock" }}-1
      - v1-dependencies-

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: yarn install --frozen-lockfile

step_save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
      - packages/cli/node_modules
      - packages/core/node_modules
      - packages/cli-plugin-init/node_modules
      - packages/cli-plugin-add/node_modules
      - packages/cli-plugin-lint/node_modules
      - ~/.cache/yarn
    key: v1-dependencies-{{ checksum "yarn.lock" }}-1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run: yarn test --ci


workflows:
  version: 2
  ci:
    jobs:
      - test