# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: publish release

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          git config --local user.email "18570148691@163.com"
          git config --local user.name "ggwujun"
          git remote set-url origin "https://$GITHUB_ACTOR:$NODE_AUTH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git checkout $CI_COMMIT_REF_NAME
          npm config set registry http://registry.npmjs.org/
          npm config set  //registry.npmjs.org/:_authToken=$PUB_NPM_ACCESS_TOKEN
          npm config set scope "@winfe"
          yarn install
          yarn run bootstrap
          git checkout .
          yarn run build
          yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUB_CI_ACCESS_TOKEN}}
          PUB_NPM_ACCESS_TOKEN: ${{secrets.PUB_NPM_ACCESS_TOKEN}}
